- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true



- name: copy configuration file
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/sites-enabled/default